### ISSUE TITLE
Adjust containers to new structure

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#1026]
## Is your feature request related to a problem? Please describe

Right now the containers expect the old structure of a single mono-repo.

## Describe the solution you'd like

- build in the same Dockerfile
- don't copy build fragments into the prod image
- adjust naming of sources(new repos, even if empty so far)

**Comment by aceppaluni** [comment]
Hi, I can take this on!

**Comment by aceppaluni** [comment]
Still working

**Comment by aceppaluni** [comment]
still working

**Comment by Idrinth** [comment]
möp

**Comment by aceppaluni** [comment]
Still working

**Comment by Idrinth** [comment]
nope
