### ISSUE TITLE
Add errors field in the /projects endpoint's sample response

### ISSUE THREAD

**Issue by marikadeveloper** [Idrinth/api-bench#1058]
## Is your feature request related to a problem? Please describe

I was implementing the history website and the first view requires a bar chart showing the number of errors for each project related to a certain date.

## Describe the solution you'd like

The current response is something like this:
```js
      project_code: {
        '2024-03-29': {
          mean: 2323324,
          average: 1324112,
          stdev: 1212,
        },
        '2024-03-30': {
          mean: 2323324,
          average: 1324112,
          stdev: 1212,
        },
        '2024-03-31': {
          mean: 2323324,
          average: 1324112,
          stdev: 1212,
        },
      },
      another_project_code: {
        '2024-03-29': {
          mean: 1323324,
          average: 2324112,
         ... and so on
```
I think just adding a field 'errors' of type number could suffice.

## Additional context

The file that contains the response is `src/routes/projects.ts`

**Comment by Idrinth** [comment]
error output:
```js
errors: {
   total: 32,
   'my error message': 23,
   'secong': 9
}
```

**Comment by Idrinth** [comment]
added the error-rate instead, I think for a project that is more useful
