### ISSUE TITLE
Add core team info to the public organisation readme

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#1061]
## Is your feature request related to a problem? Please describe

Right now people do not have a clue who is doing what, so we should change that.

## Describe the solution you'd like

We have 4 groups that are relevant:

- Core Developers: @IagoMota @itsmacr8 @aceppaluni @akhil0203 @hussainnaqvee 
- Reviewers: @marikadeveloper @Idrinth
- Quality Assurance: @jauntyjocularjay
- Moderators: @BrinaBre

Please provide a short sentence for yourself to introduce yourself to viewers of the org. Additionally add a link to their github profile and a profile picture.
Every part should contain a short summary of their "duties":

- Core Developers: Take up tasks across the issues repository on a regular basis and raise issues where needed to improve the project
- Reviewers: The same tasks as core developers as well as reviewing and merging pull requests while upholding out standards.
- Quality Assurance: The same tasks as core developers as well as guiding the creation of tests.
- Moderators: Moderate internal and external texts written where necessary.

**Comment by Idrinth** [comment]
Idrinth: A webdeveloper with 14 years of work experience, always exited to learn more and help others learn.

**Comment by akhil0203** [comment]
Akhil : I'm a master's student with experience in web development gained through open source contributions and research projects, and I believe in learning through hands-on experiences and sharing knowledge.

**Comment by akhil0203** [comment]
Akhil: I'm a master's student with experience in web development gained through open source contributions and research projects, and I believe in learning through hands-on experiences and sharing knowledge.

**Comment by hussainnaqvee** [comment]
Hussain Ali: I am a software engineer with 2 years of experience, contributing to open-source projects to learn and experience new technologies.
[github](https://www.github.com/hussainnaqvee)

**Comment by aceppaluni** [comment]
Angelina: I am a core developer with over a year of experience working on self-made projects and contributing to open-source projects enhancing my skills.

**Comment by marikadeveloper** [comment]
Marika: Italian frontend developer with 5+ years of work experience and a passion for coding since 2014. Currently pursuing a Computer Science Bachelor's while contributing to open source and exploring singing in free time.

**Comment by jauntyjocularjay** [comment]
Jay: American hobbyist developer working in Quality Assurance since 2020. Always looking for problems to tackle and new skills to acquire.

**Comment by Idrinth** [comment]
@aceppaluni you need a different profile image :D the default one does not scale properly: https://github.com/idrinth-api-bench/.github/blob/the-one/profile/README.md

Added everyone who commented so far.

**Comment by IagoMota** [comment]
I'm a software engineer who is in love with all aspects of technology, specially low level coding :D

**Comment by Idrinth** [comment]
> I'm a software engineer who is in love with all aspects of technology, specially low level coding :D

added
