### ISSUE TITLE
add unit tests

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#1062]
Test both available methods with mocha and chai.

**Comment by vr-varad** [comment]
I would to work on this issue, I have experience with mocha and chai.
Any further info on this issue would be helpful.

**Comment by Idrinth** [comment]
> I would to work on this issue, I have experience with mocha and chai. Any further info on this issue would be helpful.

Welcome in, this is referring to the two untested methods in the chartjs stdev filler repository. We have manual testing to prove they work, but I fear there may be edge cases yet to be discovered and automated testing would help a lot in keeping the plugin free of issues.

https://github.com/idrinth-api-bench/chartjs-plugin-stdev-filler/blob/the-one/src/index.ts#L16
https://github.com/idrinth-api-bench/chartjs-plugin-stdev-filler/blob/the-one/src/index.ts#L41
