### ISSUE TITLE
create ci pipeline

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#1063]
## Is your feature request related to a problem? Please describe

We have no ci in the project yet.

## Describe the solution you'd like

Add our default workflows, so that the project is properly analyzed and tested

**Comment by vr-varad** [comment]
@Idrinth As my first PR is merged, I want to work on this issue.

**Comment by Idrinth** [comment]
would be great, thank you @vr-varad :)

**Comment by vr-varad** [comment]
@Idrinth Sorry, I couldn't do it due to personal reasons, but I am free, is there any more info regarding this issue that is required to resolve this issue?
Is there any particular integration required and for which repo does the ci apply to?

**Comment by Idrinth** [comment]
> @Idrinth Sorry, I couldn't do it due to personal reasons, but I am free, is there any more info regarding this issue that is required to resolve this issue? Is there any particular integration required and for which repo does the ci apply to?

All good. The component label tells you what repo this is related to. We need at least knip, eslint, commit linting and markdownlint

**Comment by vr-varad** [comment]
@Idrinth Sorry, everything ci u mentioned is already present in chartjs stdev filter
![image](https://github.com/idrinth-api-bench/issues/assets/114755221/c0272e74-fa0f-4ed1-87bc-6cdd4e60ec8f)

**Comment by vr-varad** [comment]
Is there anything more I could add??

**Comment by Idrinth** [comment]
> @Idrinth Sorry, everything ci u mentioned is already present in chartjs stdev filter!

this lacks the files in .github/workflows completely

**Comment by Idrinth** [comment]
done somehow
