### ISSUE TITLE
Add issue repo link to all repository readmes(exception: profile readmes)

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#1065]
## Is your feature request related to a problem? Please describe

A person mentioned, that they couldn't find a way to add issues.

## Describe the solution you'd like

Very high at the top of all repo readmes there is a link to this repo's issues with an explanation, that this is the central issue hub.

**Comment by Yuvraj-Singh01** [comment]
Assign please :)

**Comment by Idrinth** [comment]
thank you!
