### ISSUE TITLE
Arabic Translation

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#1090]
## Context

- Language: Standard Arabic
- Translator: someone
- Project: Documentation Website

**Comment by ZakiNata** [comment]
Hi @Idrinth ,

Am a native Arabic speaker, I think that I can help but am not familiar with the framework or its website (found this issue while searching GitHub)

Can you please provide more details on what is needed? then I'll be able to tell whether I can do it or not
Is it like one file where I need to translate the labels from the website? 

Notice that you may need to address the issue of RTL cause unlike English, Arabic is a right-to-left language

Thanks

**Comment by Idrinth** [comment]
> Hi @Idrinth ,
> 
> Am a native Arabic speaker, I think that I can help but am not familiar with the framework or its website (found this issue while searching GitHub)

hi, thanks for your interest! The translations are done in yaml files in the language folder. It is pretty much the following scheme:

```
translation_key: "language specific text"
```

> Can you please provide more details on what is needed? then I'll be able to tell whether I can do it or not

copy the en.yml from the language folder and change the quoted strings to arabic text.

> Is it like one file where I need to translate the labels from the website? 

yes, exactly :)

> Notice that you may need to address the issue of RTL cause unlike English, Arabic is a right-to-left language

Will be adding support for that asap, it's been on my todo list for a while.

**Comment by ZakiNata** [comment]
Thanks for the explanation :) 

I'll take it from here

**Comment by ZakiNata** [comment]
Hi @Idrinth,

Translation ready under PR 154

**Comment by Idrinth** [comment]
> Hi @Idrinth,
> 
> Translation ready under PR 154

Thank you, was sadly sick for a while - sorry about the long wait
