### ISSUE TITLE
Contributors is show instead of Contributing

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#1106]
![image](https://github.com/idrinth-api-bench/issues/assets/7874631/1625e291-176e-4f8c-8719-48440231fe21)

Likely the language file or the header component have a typo.

Language Component: language/en.yml
Navigation: /src/components/main-navigation.tsx
Language Key: nav.contributing

Either in the language file or the navigation there is a mistake, likely a tiny typo.

**Comment by ChikezieI** [comment]
Hello! I will take that

**Comment by hussainnaqvee** [comment]
I want to take this issue.

**Comment by Idrinth** [comment]
> I want to take this issue.

thank you! Feel free to self-assign

**Comment by Hachondeoro** [comment]
@Idrinth Can I get assigned this issue?

**Comment by hussainnaqvee** [comment]
@Idrinth Added the required change in this [PR](https://github.com/idrinth-api-bench/documentation-website/pull/155)
