### ISSUE TITLE
calendar on homepage is missing a decent minimum height

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#1115]
![grafik](https://github.com/user-attachments/assets/546d70c3-c1ff-42b4-ab36-b018446b4e6c)

- go to the homepage
- scroll down
- see issue

Please add a height of 500px to the calendar's css in the calendar component.

**Comment by Gurbeer-Sokhi** [comment]
On it!

**Comment by nayelimdejesus** [comment]
I'd like to work on this issue.

**Comment by Idrinth** [comment]
> I'd like to work on this issue.

thank you! If you need anything, just ask :)

**Comment by MuhammadMaaz169** [comment]
I'd like to work on this issue.

**Comment by MuhammadMaaz169** [comment]
https://github.com/idrinth-api-bench/documentation-website/pull/172

**Comment by MuhammadMaaz169** [comment]
@Idrinth, i fixed the issue in the [PR](https://github.com/idrinth-api-bench/documentation-website/pull/172)
