### ISSUE TITLE
Replace Reddit with daily.dev

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#1117]
## Is your feature request related to a problem? Please describe

Reddit seems to not be used a lot in regards to what we are tackeling.

## Describe the solution you'd like

Replace the link to reddit with a link to daily dev, so we can grow that community instead.

## Additional context

Link: https://dly.to/ra0ANxPXhwl

**Comment by Benmburu** [comment]
Hey Björn, I'd like to solve this issue.

**Comment by Idrinth** [comment]
> Hey Björn, I'd like to solve this issue.

That'd be great, thank you! Do you need more info on anything?

**Comment by Benmburu** [comment]
> > Hey Björn, I'd like to solve this issue.
> 
> That'd be great, thank you! Do you need more info on anything?

yeah, where/ how do I do this?

**Comment by Idrinth** [comment]
> > > Hey Björn, I'd like to solve this issue.
> > 
> > 
> > That'd be great, thank you! Do you need more info on anything?
> 
> yeah, where/ how do I do this?

It is in the documentation-website repository. You would need to find and add a logo, remove the reddit logo and exchange the social link in the social nav component.
