### ISSUE TITLE
Fix persistent navigation dropdown 

### ISSUE THREAD

**Issue by kln98** [Idrinth/api-bench#1125]
## Describe the bug

Navigation dropdown persists after selecting parent navigation.

## To Reproduce

1. Hover over  'Contributors' 
2. Click on any sub navigation item
3. Click on "Usage"

## Expected behavior

The navigation menu should disappear after selection

## Screenshots

![image](https://github.com/user-attachments/assets/10ae0b7f-e7d6-4c51-848c-d5069be462c1)

## System

please complete the following information:

## Additional context

This will linger throughout until website is refreshed.

**Comment by Idrinth** [comment]
Since we talked about it, I assigned you - have fun :)

**Comment by Hachondeoro** [comment]
@Idrinth Can you assign the issue to me?

**Comment by Idrinth** [comment]
> @Idrinth Can you assign the issue to me?

sure, go right ahead!

**Comment by ROHIT-TECH-UNIVERSE** [comment]
@Idrinth can i solve this issue please ?? if u wish to assign me......

**Comment by Idrinth** [comment]
> @Idrinth can i solve this issue please ?? if u wish to assign me......

forgot to merge the PR, this has been solved, sorry
