### ISSUE TITLE
Generate the website translation jsons from yaml sources

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#195]
**Is your feature request related to a problem? Please describe.**
YAML is way easier to read for people who don't know how to code. Moving to it will decrease the difficulty of contributing.

**Describe the solution you'd like**
The build process reads in the yaml files from website/languages/{lang}.yml and generates minified jsons at website/dist/locales/{lang}/translation.json

The existing tool for minification should be rewritten to achieve that.

**Comment by madina0801** [comment]
I'm here :)
