### ISSUE TITLE
add a command line option to only run a specific case id

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#203]
**Is your feature request related to a problem? Please describe.**
for #52 we need the ability to test different test separately. It is also useful when you only want to check a specific part of your api because changes didn't impact all of it.

**Describe the solution you'd like**
add a command line option to the benchmark runner and a config to the main.tsx, that filters out any main-tasks, that doesn't have the specified id.

**Comment by Idrinth** [comment]
@madina0801 this could be something interesting for you if you are interested :)

**Comment by madina0801** [comment]
Looks interesting! I'm not sure how to solve it now, but I'd definitely give it a try. Is it needed to get done without external libraries? I'm thinking about something like commander or yargs :)

**Comment by Idrinth** [comment]
Since breaking the interface of the binary is not an option, likely neither yargs nor commander work right now(but can be revisited for 3.0.0). If you can get either of them to work without it breaking backwards compatibility, feel free to use them :)

https://github.com/Idrinth/api-bench/blob/master/framework/src/build-task-list.ts is where you could do the actual filtering.

**Comment by madina0801** [comment]
I'll take a closer look tomorrow or in a couple days :)

**Comment by madina0801** [comment]
I'm sorry, but where can I find benchmark runner file? I'm thinking about using process.argv :)

**Comment by Idrinth** [comment]
> I'm sorry, but where can I find benchmark runner file? I'm thinking about using process.argv :)

sorry, forgot to add that. it's `framework/bin/run-benchmark.js`, that is calling `framework/src/cli/bench.ts` with argv as parameter.

**Comment by madina0801** [comment]
Okay, I see the implementation as following:
1. Filter out main tasks in build-task-list.ts
2. Update the main.tsx config {taskId: null}
3. Modify the benchmark-run.js: create a function to parse command line args
4. Filter tasks based on the taskId in main.tsx
If I understood correctly what's needed to be done :)

**Comment by Idrinth** [comment]
> Okay, I see the implementation as following:
> 
>     1. Filter out main tasks in build-task-list.ts

yes

>     2. Update the main.tsx config {taskId: null}

would prefer `{taskId?: string}`, so it is either undefined or a string

>     3. Modify the benchmark-run.js: create a function to parse command line args

yes, there is a some functionality for that already. Feel free to also adjust the run-loadtest if desired

>     4. Filter tasks based on the taskId in main.tsx

main should remain as low logic as possible, the filtering as stated above, should be in the build-task-list.ts

>        If I understood correctly what's needed to be done :)

:) looks good

**Comment by Idrinth** [comment]
hi @madina0801 if you want to discuss the topic or get some feedback we can also setup a call via for example teams or discord. Your first try looked pretty good.
