### ISSUE TITLE
Adjust contributing guidelines: Project and custom fields

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#228]
**Context**
We have a single project, that is added to all issues and pull requests automatically. It provides a few custom fields to help guide developers, testers, translators and all other contributors to where they can most likely help and what to expect of the issue.

**Goal**
Adjust the `README.md`, `CONTRIBUTING.md` and the `website/src/pages/contributing/index.tsx` to highlight the project features, so they are easier to use for newcomers.

**Comment by Idrinth** [comment]
![image](https://github.com/Idrinth/api-bench/assets/7874631/36bd0f23-40d5-4463-b9a5-7a563d614158)

**Comment by harmeet01singh** [comment]
A bit confused about this. What exactly is meant by highlighting the project features?

**Comment by Idrinth** [comment]
> A bit confused about this. What exactly is meant by highlighting the project features?

Hi, I'm referring to the additional information available in the project. See the screenshot above as well :)

**Comment by harmeet01singh** [comment]
Apologies, but I am still just as clueless as before. Can I get some reference about this.

**Comment by Idrinth** [comment]
> Apologies, but I am still just as clueless as before. Can I get some reference about this.

I'm sorry, the fault is all mine. It looks easy when you created something. The idea is adding a short paragraph to the documentation, that explains, that there is additional information available in the project linked to the issue. Currently that contains information about where it is to be solved, how big it's expected to be and what level of knowledge you'll likely need.

Since most people overlook that information and adding another 20 labels to the project makes it hard to handle, it would be valuable to help everyone find that information.
