### ISSUE TITLE
Code Highlighting doesn't respect dark mode

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#237]
## Describe the bug

The code Highlighting Plugin currently sets inline styles that prevent the dark mode from working properly.

## To Reproduce

1. Set your system to dark mode
2. navigate to /usage/autowiring/
3. See the whit-ish code box

## Expected behavior

The highlighting must respect the dark mode.

## Screenshots

![image](https://github.com/Idrinth/api-bench/assets/7874631/713447a5-8123-4248-9b06-85a4315dc3d3)

**Comment by harmeet01singh** [comment]
I would like to work on this issue. Need some help in understanding the solution first.
As much as I understand, We need to change the color scheme of the code blocks on the website.
<img width="610" alt="image" src="https://github.com/Idrinth/api-bench/assets/55615244/1c6d2bba-dde3-40e0-ac3a-6d49d12eefd6">
Is the above image a good example?

**Comment by Idrinth** [comment]
hi @harmeet01singh there is already an open merge request for the topic, so I assume that @codesak is still handling the issue.

The goal here is to make the color scheme of the code blocks no longer inline styles, so they can be adjusted to light/dark mode of the website using the existing media query.

**Comment by Idrinth** [comment]
@harmeet01singh while we wait for a response, what about tackling https://github.com/Idrinth/api-bench/issues/228 in between? It's at least as important.

**Comment by harmeet01singh** [comment]
Sure. Will start with #228 then.
