### ISSUE TITLE
Add ids to contributor listing, so you can link to a specific one

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#255]
## Is your feature request related to a problem? Please describe

It may be beneficial to provide direct links to your own contributor listing.

## Describe the solution you'd like

Every listing has an id, that can be jumped to. For that the github username seems to be the most sensible.

## Additional context

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#linking_to_an_element_on_the_same_page

**Comment by Asin-Junior-Honore** [comment]
@Idrinth please assign me this issue👨‍💻

**Comment by Idrinth** [comment]
@Asin-Junior-Honore done, thanks alot - if you have any questions just reach out :)

**Comment by Asin-Junior-Honore** [comment]
@Idrinth  please am already done with the issue but few of my checks were not successful please could you guide me on how to go about them so all checks become successful 🙏
