### ISSUE TITLE
translation JSON to YAML

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#283]
## Is your feature request related to a problem? Please describe

convert JSON to more readable YAML

## Additional context

https://github.com/Idrinth/api-bench/blob/master/website/language/en.yml

**Comment by Avijit-ap** [comment]
Hi, I Hope you're doing well. Would it be possible to specify the exact ".json " file that needs to be improved? I'm interested in collaborating.

**Comment by Avijit-ap** [comment]
Thanks for your quick response, please assign this issue to me , I will try my best to meet with expectation as a newbie.

**Comment by Idrinth** [comment]
I'm always available on linkedin, here and on discord in case you need any help :) thanks for helping!

**Comment by Avijit-ap** [comment]
I have made a pull request please check and let me know if it is acceptable or not, I will try to fix it.
