### ISSUE TITLE
Injecting a string from env without default value fails

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#294]
## Describe the bug

given a simple function route definition, that has a string-typed or untyped parameter, the value will never be injected from the environment.

from framework/src/helper/function-analyzer.ts
```ts
if (value.default === '') {
    break;
}
if (value.default[FIRST] !== '"' && value.default[FIRST] !== '\'') {
    throw new Error(language('variable_default_value', value.name));
}
value.default = value.default
    .substring(STRING_LIMITER_REMOVAL_START, value.default.length - STRING_LIMITER_REMOVAL_LENGTH);
value.value = getEnv(value.envName, value.default);
```

## To Reproduce

1. create a new route definition
2. add a single untyped parameter
3. add the respective parameter to an .env file
4. run the benchmark
5. see it error out

## Expected behavior

The empty condition is only used to figure out if quotes need to be removed, not for skipping the value assignment.

## System

please complete the following information:

- OS: any
- Version 2.6

**Comment by Idrinth** [comment]
please also add a test for that if you can - I don't want something as embarrassing repeated

**Comment by Idrinth** [comment]
2.6.1 released with a fix, so this is no longer as urgent

**Comment by ui-mo** [comment]
from framework/src/helper/function-analyzer.ts

def my_function(value: string): void {
  if (value.default === '') {
    break;
  }
  if (value.default[FIRST] !== '"' && value.default[FIRST] !== '\'') {
    throw new Error(language('variable_default_value', value.name));
  }
  value.default = value.default
    .substring(STRING_LIMITER_REMOVAL_START, value.default.length - STRING_LIMITER_REMOVAL_LENGTH);
  value.value = getEnv(value.envName, value.default);
}

**Comment by Idrinth** [comment]
hi @ui-mo I'm not sure what you want to archieve with the code in this issue

**Comment by ui-mo** [comment]
@Idrinth 
Hi Idrinth,

I noticed the issue in function-analyzer.ts regarding injecting strings from environment variables. Here's what I found:
The current code assumes value.default is always set, leading to unexpected behavior when it's missing.
Here are two potential solutions:

Provide a default value for value.default to ensure consistent behavior.
Handle the missing environment variable gracefully (e.g., log a warning, throw an error, use a different fallback).
Additionally, consider writing test cases to cover both positive and negative scenarios, including the missing variable case.

I'm happy to discuss this further and help you implement the chosen solution.

**Comment by Idrinth** [comment]
> hi @Idrinth I noticed the issue in function-analyzer.ts regarding injecting strings from environment variables. Here's what I found: The current code assumes value.default is always set, leading to unexpected behavior when it's missing.

The value.default is always set, it defaults to an empty string. The issue here is, that the code afterwards is skipped if it is empty and no filling from env occurs.

> Provide a default value for value.default to ensure consistent behavior. Handle the missing environment variable gracefully (e.g., log a warning, throw an error, use a different fallback). Additionally, consider writing test cases to cover both positive and negative scenarios, including the missing variable case.

Logging is a good idea and I'm happy about any additional test cases.

**Comment by Idrinth** [comment]
done
