### ISSUE TITLE
add linkedin group to navigation

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#297]
## Context

We have a linkedIn group for support and experience exchange. It should be linked on the website as well, maybe moving into a new sub-menu with the other external header links.

Link: https://www.linkedin.com/groups/9588634/

**Comment by AdityaBhate** [comment]
can i work on this?

**Comment by Idrinth** [comment]
sure, go right ahead :) if you need help, feel free to reach out!

**Comment by AdityaBhate** [comment]
Is this OK?
![image](https://github.com/Idrinth/api-bench/assets/98549181/84e4c0f7-0ac6-4245-bca8-bb0f9d5a63c8)


It looks cluttered, how about I rearrange them and move all the external links to a footer?
do you have any design in mind or should I do it?

(something like this?, it just a rough design)
![image](https://github.com/Idrinth/api-bench/assets/98549181/fb44af77-3879-4cdd-98cc-dbd14e55cdc9)

**Comment by Idrinth** [comment]
> It looks cluttered, how about I rearrange them and move all the external links to a footer? do you have any design in mind or should I do it?

I expected this to happen, would prefer keeping them up in the menu though. What about putting them in their own submenu? Similar to contributing

**Comment by AdityaBhate** [comment]
ok...

**Comment by AdityaBhate** [comment]
![image](https://github.com/Idrinth/api-bench/assets/98549181/5cac452b-18fd-4e8c-9234-375d707f1de5)
**something like this?
or**
![image](https://github.com/Idrinth/api-bench/assets/98549181/670e6083-cc18-4243-b166-84250fa5cc10)

---
**I still prefer it like this tho**
![Screenshot 2024-02-18 121100](https://github.com/Idrinth/api-bench/assets/98549181/d1438edb-f55e-45b5-969c-0b0eb97b8160)


Sorry for asking too many questions 😅, (i am still trying out this code base and don't want to ruin it..)

**Comment by AdityaBhate** [comment]
ok,
will get it done and do a PR by tomorrow!

**Comment by Idrinth** [comment]
no hurry, it's not urgent. Thanks for helping!

**Comment by AdityaBhate** [comment]
hey!
I added the LinkedIn group! and will push the code.
I also noticed that the website's navbar is not mobile-responsive.

after this issue is closed, can I create a new issue and make the navbar mobile responsive (using the hamburger menu)?

**Comment by Idrinth** [comment]
> after this issue is closed, can I create a new issue and make the navbar mobile responsive (using the hamburger menu)?

yes, great! We made it functional for mobile, but didn't yet find time to add a way to minimize the menu
