### ISSUE TITLE
wrong name for sponsors.ts page test

### ISSUE THREAD

**Issue by GeorgeSchafer** [Idrinth/api-bench#299]
## Describe the bug

sponsors.ts is not recognized by cypress due to file name

## To Reproduce

1. cd website
2. run Cypress
3. e2e
4. note lack of page

## Expected behavior

Page should appear

## Screenshots

already fixed

## System

please complete the following information:

- OS: Windows
- Version: 10

**Comment by Idrinth** [comment]
fixed
