### ISSUE TITLE
Second Navbar "Home" Label Formatting Issue

### ISSUE THREAD

**Issue by Avijit-ap** [Idrinth/api-bench#312]
## Describe the bug
The label name "Home" in the second navigation bar is not formatted properly. It appears to be cut off and misaligned.

To Reproduce
Go to the IAB / api-bench homepage.
Look at the second navigation bar.
Observe that the label name "Home" is not formatted properly.

## Expected behavior
The label name "Home" should be fully displayed and aligned correctly within the second navigation bar.

## Screenshots
This screenshot showcasing the incorrect formatting of the "Home" label in the second navigation bar. 

![Home_label_not _formated](https://github.com/Idrinth/api-bench/assets/56922114/4834b9c4-d89a-48ed-a808-31bc2859ac58)

This screenshot showcasing the correct formatting of the "Home" label on another page. 
![Home_label_proper_but_need_fix](https://github.com/Idrinth/api-bench/assets/56922114/e2c5b133-3896-4da0-aa25-9650512985e2)

Also " Home > Quick Start " **not aligned properly** 

## System
- OS: [e.g. Windows 10]
- Version: [e.g. 21H2]
- Browser: [e.g. Chrome]
- Version: [e.g. 103.0.5060.54]

## Additional context

This is issue is impacting the webpage viewing experience

**Comment by Avijit-ap** [comment]
Hi @Idrinth , hope you're fine. I want to work in this UI issue on the webpage. Let me know if it worth a fix.

**Comment by Idrinth** [comment]
it looks like some fine-tuning for media queries is required - all yours @Avijit-ap :)

**Comment by Idrinth** [comment]
hi @Avijit-ap, how is it going?

**Comment by Avijit-ap** [comment]
Sorry for giving you no update, I couldn't solve it but want to discuss on the issue. Please expect the updates within this week

**Comment by Idrinth** [comment]
no worries, @Avijit-ap , feel free to drop by on the slack for example for discussion and help - I'll make sure we get you unstuck :)

**Comment by Idrinth** [comment]
solved to my knowledge
