### ISSUE TITLE
Middleware usage: Extend description

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#331]
## Context

We are currently lacking a description on how to apply middlewares to routes. This means new persons starting may or may not know how to handle this central aspect.

**Comment by aceppaluni** [comment]
Hi, Were you thinking of adding this description to the README or somewhere within the main page page of Contributing?

**Comment by Idrinth** [comment]
I thought about adding a paragraph and an example to /usage/routes

**Comment by aceppaluni** [comment]
Sounds good :)
