### ISSUE TITLE
Header navigation is wider than the screen at ~tablet size

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#336]
## Describe the bug

Some screen resolutions between the current mobile and desktop view don't show the entire navigation bar.

## To Reproduce

1. Go to the website
2. Slowly reduce the width of your window
3. Notice that the outmost elements disappear of the screen

## Expected behavior

There should be a media query preventing the loss of navigation options,

## Screenshots

![image](https://github.com/Idrinth/api-bench/assets/7874631/705d81b2-8d29-48aa-9702-0b75ee6c524b)

**Comment by AnukratiMehta** [comment]
I'd like to give this a try @Idrinth

**Comment by Idrinth** [comment]
Thanks! gave you the issue - reach out if you need anything :)
