### ISSUE TITLE
Add missing react linting to website

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#349]
## Context

We are currently missing react specific linting rules, so some of the code is unlinted.

## Project

https://github.com/jsx-eslint/eslint-plugin-react

**Comment by aceppaluni** [comment]
Hi @Idrinth Is this issue still open? If so, I would like to contribute.

**Comment by Idrinth** [comment]
hi @aceppaluni yes, the issue is still open, feel free to introduce the library for the website and fix what it finds :)

**Comment by aceppaluni** [comment]
@Idrinth thank you! I am a first time contributor and I wanted to make sure I have the correct understanding before proceeding. I understand that in order to enable the react specific linting rules both the plugin and extends would need to be adjusted. Is this correct?

**Comment by Idrinth** [comment]
@aceppaluni yes, that is correct. If you need any help, feel free to contact me, I'm usually available :)

A link to help:
https://eslint.org/docs/latest/use/configure/

**Comment by aceppaluni** [comment]
@Idrinth Perfect, thank you!!! I am attempting to clone the repository but I am getting an error. I am not sure If I am cloning the correct repo. I attempted to clone the link from above.

**Comment by Idrinth** [comment]
> @Idrinth Perfect, thank you!!! I am attempting to clone the repository but I am getting an error. I am not sure If I am cloning the correct repo. I attempted to clone the link from above.

You want to clone this repository. see the contributing guidelines for a step to step guide https://idrinth-api-ben.ch/contributing/

**Comment by aceppaluni** [comment]
@Idrinth Thank you! Which .eslintrc file is the correct one? I see a few in the repo.

**Comment by Idrinth** [comment]
> @Idrinth Thank you! Which .eslintrc file is the correct one? I see a few in the repo.

the one in the website folder - they all share some basic settings(that is the root one), but there is a specific one for each project part.

**Comment by aceppaluni** [comment]
@Idrinth , this would be the file labeled .eslintrc.cjs ?

**Comment by Idrinth** [comment]
> @Idrinth , this would be the file labeled .eslintrc.cjs ?

exactly

**Comment by aceppaluni** [comment]
@Idrinth thank you!

**Comment by aceppaluni** [comment]
@Idrinth I am attempting to push the changes and I am returned an error. The error reads "remote: Permission to idrinth/api-bench.git denied to aceppaluni.
fatal: unable to access 'https://github.com/idrinth/api-bench/': The requested URL returned error: 403"

**Comment by aceppaluni** [comment]
I created the fork but I am still returned the same error

**Comment by Idrinth** [comment]
> @Idrinth , I created the fork but I am still returned the same error

then you are not pushing to the fork, set your origin correctly please :)
https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories

**Comment by aceppaluni** [comment]
I set the origin and I am returned a message saying "remote origin already exists".

**Comment by aceppaluni** [comment]
@Idrinth I was able to get to the point where I can push the changes, however, after typing 'git push origin HEAD' i am returned the same error from before.

**Comment by Idrinth** [comment]
> @Idrinth I was able to get to the point where I can push the changes, however, after typing 'git push origin HEAD' i am returned the same error from before.

got about 30mins, feel free to hop into https://meet.google.com/pzp-barz-wid so we can have a look together. From your description I'm not sure what is wrong.

**Comment by aceppaluni** [comment]
@Idrinth I am currently at work and am unable to connect. I think I was able to submit the pull request. Please let me know if there is anything you need from me, thank you! :)

**Comment by Idrinth** [comment]
> @Idrinth I am currently at work and am unable to connect. I think I was able to submit the pull request. Please let me know if there is anything you need from me, thank you! :)

the pull request is near perfect, please just have a quick look at the issues found by eslint and repair them if you can. I doubt it's anything complicated :)

**Comment by aceppaluni** [comment]
@Idrinth I will fix them as soon as I can, thank you 😄

**Comment by aceppaluni** [comment]
@Idrinth I am working on correcting the error however I am unable to determine the cause of the issue. Initially, I removed the "react-refresh" plugin as the documentation did not include this and I was getting error when keeping both plugins. When doing so I encountered a new error. I added the plugin back to the file but I am now returned the initial issue.

**Comment by Idrinth** [comment]
> @Idrinth I am working on correcting the error however I am unable to determine the cause of the issue. Initially, I removed the "react-refresh" plugin as the documentation did not include this and I was getting error when keeping both plugins. When doing so I encountered a new error. I added the plugin back to the file but I am now returned the initial issue.

Clicking on details would bring you to the cause. see https://github.com/Idrinth/api-bench/actions/runs/8074507081/job/22059908150?pr=365
