### ISSUE TITLE
Add an FAQ to the bottom of the start page

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#360]
## Context

Currently we have no easy to read and maintain FAQ about the benefits and usage options of api-bench. This may make it harder for people to adopt it.

Suggested Questions:

- What is benchmarking
- What is load testing
- How long does it take to write a test
- How long does it take to setup

**Comment by aceppaluni** [comment]
@Idrinth Are you looking to add an FAQ section to the index.tsx file located in Website/src/pages/home/index.tsx?

**Comment by Idrinth** [comment]
> @Idrinth Are you looking to add an FAQ section to the index.tsx file located in Website/src/pages/home/index.tsx?

yes, exactly. I'm trying to reduce the barrier to entry as much as I can, so it's easy to try out and get value out of the tool.

**Comment by aceppaluni** [comment]
@Idrinth perfect, thank you!
