### ISSUE TITLE
Add a way to add none-code contributors

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#362]
## Is your feature request related to a problem? Please describe

We currently have two people who contributed, but can not be listed by github, since they didn't provide code. I would like to also list them as contributors, just as a separate list.

## Describe the solution you'd like

Set up two subheaders under contributors: "Code contributors" and "Non-Code contributors". They both get data from a json file each, where the NCC have a hardcoded file and the CC have a generated file. Headers for an empty category must not be displayed.
The followwing fields should be available:
```ts
interface NonCodeContributor {
  name: string;
  url: string;
  contributions: string;
  location: string;
  intro: string;
}
```

**Comment by aceppaluni** [comment]
Hi! Is this still open?

**Comment by Idrinth** [comment]
hi @aceppaluni yes it is. Not very urgent, but if you are interested feel free to take it :)

**Comment by aceppaluni** [comment]
Of course! For those who did not contribute code, is there a certain way you would like them to be added? Where are the interfaces and data files located for both CC and NCC?

**Comment by Idrinth** [comment]
> Of course! For those who did not contribute code, is there a certain way you would like them to be added? Where are the interfaces and data files located for both CC and NCC?

CC has a json generated in /website/src/contributors.json automatically, no interface file exists so far.
NCC has no file so far, neither json nor interface. I would prefer a similar setup to the contributors.json. Adding has to be done manually, due to there not being a data source to draw from.

**Comment by aceppaluni** [comment]
No problem, I can make a hardcoded data file for the NCC and leave it in the contributors folder. Are the interfaces required or were they provided as template to follow? I am planning to add an additional <div></div> container to wrap around the els element. Please let me know if this is okay as I do not want to interfere with the CSS   :)

**Comment by aceppaluni** [comment]
Hi! I have created a data file and container for the NCC contributions. Do you have the names, urls, contributions, locations, bios, and images of those who assisted in the project? I will go ahead and add it to the data file :)

**Comment by Idrinth** [comment]
> No problem, I can make a hardcoded data file for the NCC and leave it in the contributors folder. I am planning to add an additional div container to wrap around the els element. Please let me know if this is okay as I do not want to interfere with the CSS :)

Not sure if that is necessary, but sure, go ahead, I'll have a look at your result :)

> Hi! I have created a data file and container for the NCC contributions. Do you have the names, urls, contributions, locations, bios, and images of those who assisted in the project? I will go ahead and add it to the data file :)

Waiting for data there, you have to test with made up data sadly :(

**Comment by aceppaluni** [comment]
No problem, I am can create filler data :) Thank you!
