### ISSUE TITLE
replace propTypes with typescript implementation

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#403]
```ts
import { Tag, TagProps } from '*****';

const COLOR = 'blue';

interface SampledTagProps extends TagProps {
  show?: boolean;
}

export function SampledTag({ show, ...props }: SampledTagProps) {
  return (show !== undefined ? show : false) ? (
    <Tag color={COLOR} className="datadiff-sampled-tag" {...props}>
      sampled
    </Tag>
  ) : null;
}
```

**Comment by kofta999** [comment]
Hello, may I work on this issue?

**Comment by Idrinth** [comment]
hi @kofta999 , of course! If you need help, let me know :)

**Comment by kofta999** [comment]
Thank you!

I understood the general idea of the issue but I didn't really understand the example above, would really appreciate it if you explained it.

**Comment by Idrinth** [comment]
https://dev.to/amanhimself/prop-types-in-react-and-typescript-1kph have a look at the "Using type keyword to declare prop type definitions" part.

**Comment by kofta999** [comment]
Thank you, this is also was the idea I had in mind but wanted to confirm as I got confused by the extended interface in the example. Will start working on it asap, thanks again!

**Comment by kofta999** [comment]
Hello again, I wanna ask about something
https://github.com/Idrinth/api-bench/blob/2769d3f054f9d62da272dfbfc6d5c1113d101266/website/src/components/lang.tsx#L8-L24
Shouldn't children be a react component type not a string? and should it also be optional?

As here for example `Link` does not have children
https://github.com/Idrinth/api-bench/blob/2769d3f054f9d62da272dfbfc6d5c1113d101266/website/src/components/breadcrumbs.tsx#L13-L35

**Comment by Idrinth** [comment]
> Hello again, I wanna ask about something
> 
> https://github.com/Idrinth/api-bench/blob/2769d3f054f9d62da272dfbfc6d5c1113d101266/website/src/components/lang.tsx#L8-L24
> 
> Shouldn't children be a react component type not a string? and should it also be optional?
> 
> As here for example `Link` does not have children
> 
> https://github.com/Idrinth/api-bench/blob/2769d3f054f9d62da272dfbfc6d5c1113d101266/website/src/components/breadcrumbs.tsx#L13-L35

The link usually does not have children, but would support a single string child - the key to translate. I think you can remove that logic part, it shouldn't be used anymore and was just there for backwards compatibility.

**Comment by kofta999** [comment]
Understood, so I should remove the children prop completely and return
```jsx
<Trans t={t} i18nKey={lnkey}>{lnkey}</Trans>
```
instead, correct?

**Comment by Idrinth** [comment]
> Understood, so I should remove the children prop completely and return
> 
> ```js
> <Trans t={t} i18nKey={lnkey}>{lnkey}</Trans>
> ```
> 
> instead, correct?

yes please
