### ISSUE TITLE
Commit messages

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#406]
## Context

We currently don't have a standard commit message template. Please add one to the contributor guidelines, that make sense to this project.

## System

[Example](https://gist.github.com/brianclements/841ea7bffdb01346392c)

**Comment by savvy-itch** [comment]
Hello, I'd like to give it a go. Is this issue still vacant?

**Comment by Idrinth** [comment]
this is vacant, thanks @savvy-itch
