### ISSUE TITLE
Bug: Multi-Line menu at medium screen width

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#424]
## Describe the bug

We have a multi line navigation at medium width views. This is a bit confusing.

## To Reproduce

1. Go to any page of the website
2. reduce the browser width to about 750px

## Expected behavior

The external links(npm, github, linkedin) should move into a sub-menu to prevent multi line navigation.

## Screenshots

![image](https://github.com/Idrinth/api-bench/assets/7874631/7109ebb8-70b3-4877-8f1f-b0906b75dc1b)

## Additional context

The submenu can also be available in the mobile view to reduce the header size. It is not necessary though.

**Comment by savvy-itch** [comment]
I'd like to work on this.

**Comment by Idrinth** [comment]
go right ahead @savvy-itch ! thanks

**Comment by Idrinth** [comment]
no longer an issue
