### ISSUE TITLE
gdpr compliance

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#428]
## Is your feature request related to a problem? Please describe

Right now we don't have a cookie warning and consent for the trackable data. This does not follow EU regulations.

## Describe the solution you'd like

Please add a cookie consent solution, to be compliant, for example https://www.npmjs.com/package/vanilla-cookieconsent

## Additional context

We are currently using tracking with matomo and functional local storage for light/dark mode.

**Comment by KirilCycle** [comment]
Hello! In which file are cookies set and how (i have not found it)? Should this cookie warning also have a separate "Manage Settings" page?  I am also interested in functional local storage for light/dark mode, I switched the theme but the local storage is always empty.

**Comment by Idrinth** [comment]
> Hello! In which file are cookies set and how (i have not found it)? Should this cookie warning also have a separate "Manage Settings" page? I am also interested in functional local storage for light/dark mode, I switched the theme but the local storage is always empty.

Feel free to implement that page! You don't have to use the library if it doesn't make sense from your perspective. Please open a separate issue for the light/dark mode switch.
Matomo is set via external script that is loaded in tracking.ts - that part needs to be adjusted

**Comment by KirilCycle** [comment]
Hello! I added the en translation to the modal translation, but the locales files are in the gitignore file, should I leave the text instead of the 'Lang' component?

**Comment by Idrinth** [comment]
> Hello! I added the en translation to the cookie consent modal, but the locales files are in the gitignore file, should I leave the text instead of the 'Lang' component?

the translations go innto the filess sin /language - the other files are generated form that via the `npm run language` command
