### ISSUE TITLE
Dark/Light mode switch is placed weirdly on mobile

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#431]
## Describe the bug

Currently the dark/light mode switch is placed below the navigation on mobile. That is rather unexpected.

## To Reproduce

1. Go to the website
2. Scale it to mobile

## Expected behavior

Usually the dark/light switch is near or at the top.

**Comment by Hbrehman** [comment]
can I work on this issue?

**Comment by Idrinth** [comment]
hi @Hbrehman , feel free to do this! If you need help, let me know.
