### ISSUE TITLE
Create FAQ-Component

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#433]
## Is your feature request related to a problem? Please describe

Right now out FAQ is hard to read and process, since it doesn't look the part.

## Describe the solution you'd like

Create a component, that gets title and answer(string or array of strings) and displays that as a bar, that only shows the title. On click that bar opens up and presents the answer in a box below it.

Please replace the FAQ-entries on the main page with that component.

**Comment by ishubhamsharma7** [comment]
Hi @Idrinth , I hope you are fine.  I was working on this and i create a accordion for this and this how it look like. Can you please have a look at and it and let me know if this is fine or not and i know cursor pointer is missing that i'll add. 

Plus i've set the limit of 3 titles only

https://github.com/Idrinth/api-bench/assets/47591431/6de34c7a-5835-48ab-9eb3-9dc443f4d37f

**Comment by Idrinth** [comment]
@ishubhamsharma7 welcome in! The solution looks like a good start, but was meant for the already existing question-answer pairs right below that.
Would be nice if the look of the headers was a bit more button-like, so people actually recognize them as clickable.

**Comment by ishubhamsharma7** [comment]
@Idrinth Sure will add that make it recognizable. Thanks for the feedback.

**Comment by ishubhamsharma7** [comment]
Hi @Idrinth sorry for taking your time. I've created this is this fine for you or anything else required in it.
https://github.com/Idrinth/api-bench/assets/47591431/dd24c334-fffa-4a9a-bb41-e5fa33029b9a

**Comment by ishubhamsharma7** [comment]
Hi @Idrinth, sorry for taking your time on this. Is this look fine now or anything else is required in it?
Uploading faq-dropdown.mov…

**Comment by ishubhamsharma7** [comment]
Hi @Idrinth, sorry for taking your time on this. Is this look fine now or anything else is required in it?

https://github.com/Idrinth/api-bench/assets/47591431/b3b5e167-a763-4baf-997b-ffcb2beb9548

**Comment by Idrinth** [comment]
perfect @ishubhamsharma7 !
