### ISSUE TITLE
README / and /framework

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#489]
## Context

We need to add the relevant social buttons to the readme and link them:

- npm (only root)
- github (only framework)
- slack
- linkedin

Remove the slack section from the readme once the button has been added.

**Comment by hussainnaqvee** [comment]
Hi @Idrinth. I would like to take this issue.

**Comment by Idrinth** [comment]
> Hi @Idrinth. I would like to take this issue.

thanks, go right ahead!
