### ISSUE TITLE
Open/Close symbols of the FAQ don't display properly in Firefox

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#505]
## Describe the bug

Open/Close symbols of the FAQ don't display properly in Firefox

## To Reproduce

1. Go to the home page

## Expected behavior

The symbols should be visible in Firefox as well.

## Screenshots

![image](https://github.com/Idrinth/api-bench/assets/7874631/fa64b828-751d-41c7-96bd-db6c73d4e69d)

## System

Firefox

**Comment by Hbrehman** [comment]
can I pick this up?

**Comment by Idrinth** [comment]
> can I pick this up?

sure, thanks
