### ISSUE TITLE
Extract FAQ Element in it's own component

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#523]
## Is your feature request related to a problem? Please describe

Currently we are creating similar elements in a loop, making the handling of state harder than necessary.

## Describe the solution you'd like

Extract the state handling, title and answer of a FAQ-Item into the component `faq-item.tsx`.

**Comment by Hbrehman** [comment]
Can I pick this up?

**Comment by Idrinth** [comment]
> Can I pick this up?

yes, of course! Thank you!
