### ISSUE TITLE
Remove home button from nav

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#553]
## Is your feature request related to a problem? Please describe

Our navigation is very wide and the logo is unused.

## Describe the solution you'd like

move the nav-link to the logo and remove it from the navigation.

**Comment by shikhar13012001** [comment]
@Idrinth  I am new to this repo and would love to contribute. Can you assign this issue to me? Thanks!

**Comment by Idrinth** [comment]
Welcome in @shikhar13012001 ,
You can find  the navigation thatyou need to adjust in `documentation-website/src/components/hheader.tsx`. There you need to remove the `Home` element from the navigation and add the link to the logo instead
