### ISSUE TITLE
 header have low-contrast text on light them

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#582]
## Describe the bug

header have low-contrast text on light theme which is difficult or impossible for many users to read

## Expected behavior

Make the header gray lighter to increase the contrast.

**Comment by KirilCycle** [comment]
Can i fix this?

**Comment by Idrinth** [comment]
> Can i fix this?

sure, thanks!

**Comment by KirilCycle** [comment]
One problem background cant be light gray, only white color can pass this test with current green text color according to: #https://dequeuniversity.com/rules/axe/4.8/color 
--dark-green: hsla(132deg 33% 29% / 100%) same as rgb(50, 98, 59)

**Comment by KirilCycle** [comment]
I will apply changes also to footer  and header sub links as they have the same problem

**Comment by Idrinth** [comment]
> I will apply changes also to footer and header sub links as they have the same problem

make sure they have some way to be recognised as not part of the background please
