### ISSUE TITLE
Translations: desscribe npm run language in root

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#603]
## Is your feature request related to a problem? Please describe

If someone wants to test translations, they don't know that we have aut-rebuild by using `npm run language` in the project root.

## Describe the solution you'd like

Add to both contributing guidelines the above information.

**Comment by martincarapia** [comment]
So I'm trying to fix up the contributing guidelines for both .md and the website, but where do I find these descriptions? I'm sure it's a simple answer but I can't figure it out. Can someone point me in the right direction?

![image](https://github.com/Idrinth/api-bench/assets/78377730/856c66c6-e9bb-44a2-b27a-67385e21311d)

**Comment by Idrinth** [comment]
> So I'm trying to fix up the contributing guidelines for both .md and the website, but where do I find these descriptions? I'm sure it's a simple answer but I can't figure it out. Can someone point me in the right direction?
> 
> ![image](https://private-user-images.githubusercontent.com/78377730/319449079-856c66c6-e9bb-44a2-b27a-67385e21311d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDczMDQsIm5iZiI6MTcxMjIwNzAwNCwicGF0aCI6Ii83ODM3NzczMC8zMTk0NDkwNzktODU2YzY2YzYtZTliYi00NGEyLWIyN2EtNjczODVlMjEzMTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA1MDMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0Mjc1MjZlZGViMGI5ZWI2OTYyZDY0N2RjZDFiMjg0OTEwOTM1N2E2Y2M0OTNmOGM3ZTlkMTBjMDFmNDIyYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8a7h66VTg0FGTajj2ZWvNE1h-kgEpcHzX5Em_R1DS9E)

hi, the translations are build from the yaml files in the language folder, so /documentation-website/language/en.yml for example

**Comment by Idrinth** [comment]
Feel free to add that info to the contributing guidelines if it is missing by the way, thanks for pointing that out!

**Comment by Idrinth** [comment]
https://medium.com/idrinth-api-bench/translating-api-bench-6b375ccd17f6 may help @martincarapia

**Comment by martincarapia** [comment]
Yup, I'm looking through the page and .md to make sure things are up to date with each other.

**Comment by arnabnandy7** [comment]
I want to work on further translation in Bengali and Hindi (Indic languages). Let me know if I can start.

**Comment by Idrinth** [comment]
> I want to work on further translation in Bengali and Hindi (Indic languages). Let me know if I can start.

make an issue please and then get statrted! Thank you!
