### ISSUE TITLE
remove @media screen and (width <= 786px)

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#608]
## Describe the bug

We hhave a mobile first design. This media query contradicts that.

## Expected behavior

We don't have a smaller or equals query, but a bigger or equals than

**Comment by itsmacr8** [comment]
If I understand correctly, the default css code should not be **inside this media query** because of **mobile first**. So, I just have to remove the media query or do I need to place it **bigger or equals** media query like **@media screen and (width >= 600px)**?
