### ISSUE TITLE
Add syntax highlighting

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#61]
**Describe the solution you'd like**
use a [syntacx highlighter](https://www.npmjs.com/package/react-syntax-highlighter) to highlight the typescript and javascript codes.

**Comment by DavidSaintAnna** [comment]
![image](https://github.com/Idrinth/api-bench/assets/91479085/98b077bf-ce27-4d37-8181-cbdfd014fb8b)
added!

**Comment by Idrinth** [comment]
fixed in #67
