### ISSUE TITLE
Create a success check middleware

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#635]
## Is your feature request related to a problem? Please describe

A lot of apis provide a status field, we should provide a standard implementation to handle the most common patterns.

## Describe the solution you'd like

- success middleware(or):
  - status field is success
  - success field is true
- failure middleware(or):
  - status field is error
  - success field is false

**Comment by owais34** [comment]
Hi @Idrinth  , I would like to work on this feature 😁. Thanks !!

**Comment by Idrinth** [comment]
@owais34 go right ahead, thanks
