### ISSUE TITLE
add reddit link to socials

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#639]
Wee have a (tiny) Reddit now in case someone neeeds it. Please add it to the socials and widen them to 5/row instead of the current 4/row.

## Additional context

https://www.reddit.com/r/IdrinthApiBench/

**Comment by KirilCycle** [comment]
Hi, I can handle it, please assign me

**Comment by Idrinth** [comment]
sure, go right ahead! @KirilCycle
