### ISSUE TITLE
Tabbing on the open-arrow in the menu should not go to the target link

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#669]
## Describe the bug

We have an open symbol on menu elements with a sub menu. Clicking on that currently takes you to the menu point itself

## To Reproduce

1. Go to 'https://idrinth-api-ben.ch'
2. Click on 'Contributing's Arrow down.'
3. See error

## Expected behavior

Clicking on the symbol opens the sub menu until you click outside of that.

**Comment by simileoluwa** [comment]
Hi @Idrinth sincerely, i stand to be corrected, I seem not to see the error as explained. 

I have tried using different browsers and it seems to be functioning properly.

Could you guide with a screenshot or give more details?


Thank you

**Comment by Idrinth** [comment]
> Hi @Idrinth sincerely, i stand to be corrected, I seem not to see the error as explained.
> 
> I have tried using different browsers and it seems to be functioning properly.
> 
> Could you guide with a screenshot or give more details?
> 
> Thank you

Maybe my wording is off, sinceI  can reproduce it with both Chromium based  and Firefox based browsers.

I was  expecting, that clicking  on the arrow does not open a link, but the sub menu.

**Comment by simileoluwa** [comment]
well, as much as i have seen , it works

**Comment by Idrinth** [comment]
```html
<a aria-expanded="false" id="dropdown-contributing" aria-controls="contributing-menu" aria-current="page" class="dropdown-links-heading active" href="/contributing/">Contributing<svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" d="M0 0h24v24H0z"></path><path d="m7 10 5 5 5-5z"></path></svg></a>
```
Both in the a tag, no event attached - it can not prevent that arrow from being part of the link @simileoluwa
