### ISSUE TITLE
Add language switch to website

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#702]
## Is your feature request related to a problem? Please describe

It is currently very hard to test translations.

## Describe the solution you'd like

Add a seleect to the  footer, that switches thee desired language and stores the information in the localStorage, so that you still havee that choice upon reloading.

## Additional context

Prefill it with the currently used browser language until something else is chosen.

**Comment by marikadeveloper** [comment]
Hey! I can try to implement this, if it's okay with you

**Comment by Idrinth** [comment]
> Hey! I can try to implement this, if it's okay with you

thanks, sure!

**Comment by marikadeveloper** [comment]
Hi, is it okay like this? Or do you prefer it green like the NavLink?
<img width="946" alt="Screenshot 2024-04-22 at 20 58 10" src="https://github.com/Idrinth/api-bench/assets/116084393/dbcd8322-2cde-41ba-9fde-a76c0de561d4">
<img width="1142" alt="Screenshot 2024-04-22 at 20 58 18" src="https://github.com/Idrinth/api-bench/assets/116084393/1284ab6e-cd9f-4c7c-b0e9-40ddbf4589d4">

**Comment by Idrinth** [comment]
> Hi, is it okay like this? Or do you prefer it green like the NavLink? Or maybe uppercase language? Or maybe non-short lettering so "English" and "Français"? Or adding an icon like a globe? I can also look for open source svgs to get the flag of the country

absolutely fine, thank you! We can still improve upon it if needed
