### ISSUE TITLE
add lighthouse check for websites

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#740]
## Is your feature request related to a problem? Please describe

We currently get surprised when our metrics get worse.

## Describe the solution you'd like

use https://www.npmjs.com/package/lighthouse to compare between the live site and the current site in the runner and fail if any of top level points is worse than the live score.

**Comment by owais34** [comment]
Hi @Idrinth , I would like to work on this :).

**Comment by Idrinth** [comment]
> Hi @Idrinth , I would like to work on this :).

thank you!

**Comment by owais34** [comment]
Hi @Idrinth  , this check should be part of github workflows right ?

**Comment by Idrinth** [comment]
> Hi @Idrinth , this check should be part of github workflows right ?

exactly!
