### ISSUE TITLE
curl call to route

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#813]
## Is your feature request related to a problem? Please describe

Often tools spit out curl calls instead of useable information for us.

## Describe the solution you'd like

create a binary in the cli, that can take a curl call and convert it to a route. It should be interactive.

**Comment by owais34** [comment]
Hi @Idrinth , I would love to work on this :) .

**Comment by Idrinth** [comment]
Great, thank you @owais34!
