### ISSUE TITLE
Rename master to the-one

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#830]
## Context

Master is considered offensive by some people, considering it a reference to slavery. To make sure people are not offended we should be using a different name.

## Goal

Replace master mentions with new name:

Options:

 - the-one
 - core
 - center 
 - main
 - trunk
 - 2b-released

Opinions on what name to take, will take the most voted for in 7 days?

VOTE RESULT: `the-one`

**Comment by DavidSaintAnna** [comment]
my first option is master.
my second option would be core.

**Comment by Idrinth** [comment]
currently favoring `the-one` myself

**Comment by Idrinth** [comment]
Icah voted for `main` on linkedin

**Comment by BrinaBre** [comment]
Ich would say the one

**Comment by pas4nd** [comment]
1st choice: the-one
2nd choice: main

**Comment by stephviz** [comment]
I really only see main these days and that’s my preference too.

**Comment by marikadeveloper** [comment]
the-one is top tier for me

**Comment by Idrinth** [comment]
core 1
the-one 4
main 3
