### ISSUE TITLE
italian translation for the framework

### ISSUE THREAD

**Issue by marikadeveloper** [Idrinth/api-bench#886]
## Context

- Language: Italian
- Translator: Marika, me
- Project: Framework
- Code-Knowledge: Do I only need to create an it.yml file inside framework/language? Or there's something else?

**Comment by Idrinth** [comment]
>     * Code-Knowledge: Do I only need to create an it.yml file inside framework/language? Or there's something else?

Yes, same as everywhere, thank you!
