### ISSUE TITLE
misaligned sponsor logos

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#891]
## Describe the bug

Sponsors logos are misaligned.

## To Reproduce

1. Go to sponsors page

## Expected behavior

![image](https://github.com/Idrinth/api-bench/assets/7874631/bb90a4ea-f1cd-495d-88ea-a27a549c2300)

Top is expected, bottom is current

```css
  align-self: center;
  justify-self: center;
  background: transparent;
  border: none;
``

**Comment by hussainnaqvee** [comment]
I would like to work on this issue :smiley:

**Comment by Idrinth** [comment]
> I would like to work on this issue 😃

Go right ahead, thank you!
