### ISSUE TITLE
Active page is not highlighted in header nav

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#92]
![grafik](https://github.com/Idrinth/api-bench/assets/7874631/c8f30056-2f5a-4479-8986-2ab662c18460)
please add a darker background

**Comment by Idrinth** [comment]
solved

**Comment by Selmy44** [comment]
Hi Idrinth,
May I ask,.. Is it possible that the nav color can be changed to white ? I guess, would look more good in the dark mode with a white color and a green background ?

**Comment by Idrinth** [comment]
@Selmy44 feel free to do that, just create a new issue for that please :)
