### ISSUE TITLE
Adding Accessibility

### ISSUE THREAD

**Issue by MohamedSy1** [Idrinth/api-bench#94]
**Context**
We need to make the website more accessible for users with disability. We can add aria label inside of each header and ul.

**Comment by Idrinth** [comment]
please expand the contributing guidelines to cover that as well

**Comment by KirilCycle** [comment]
Hello! Can i handle this problem ? I also found that <button class="theme-toggle-btn"> doesn't have an accessible name

**Comment by Idrinth** [comment]
> Hello! Can i handle this problem ? I also found that `<button class="theme-toggle-btn">` doesn't have an accessible name. Also header have low-contrast text on light theme which is difficult or impossible for many users to read, and FAQ list item tabindex should have value less than 0

please stick to the aria labels for this and open a new issue for the contrast :)
