### ISSUE TITLE
add all contributors bot to the project

### ISSUE THREAD

**Issue by akhil0203** [Idrinth/api-bench#943]
## Is your feature request related to a problem? Please describe

There is need for adding non code and code contributors to root readme or contributors file automatically.

## Describe the solution you'd like

Add [all contributors app](https://github.com/all-contributors/all-contributors) to the project.

<img width="940" alt="contributors-table-small" src="https://github.com/Idrinth/api-bench/assets/101108396/244ed472-9a8c-404b-8da8-7d37f4c297c2">

**Comment by Idrinth** [comment]
> There is need for adding non code and code contributors to root readme or contributors file automatically.

Isn't https://idrinth-api-ben.ch/contributing/contributors/ already doing this for us?

**Comment by Idrinth** [comment]
hi @akhil0203 , is there still a need for the bot?

**Comment by akhil0203** [comment]
we can close this issue.
