### ISSUE TITLE
Update api-bench link on docs website

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#958]

**Comment by arnabnandy7** [comment]
I want to work on this. Please assign it to me.

**Comment by arnabnandy7** [comment]
Hi @Idrinth,
Can you give me some idea why is the following commit is failing? I'm not sure what reference it's required.

`git commit -m "documentation(documentation-website): Update api-bench link on docs website."

> @idrinth-api-bench/api-bench/root@2.7.4 commitlint
> commitlint --edit

⧗   input: documentation(documentation-website): Update api-bench link on docs website.
✖   references may not be empty [references-empty]

✖   found 1 problems, 0 warnings
ⓘ   Get help: https://idrinth-api-ben.ch/contributing/`
