### ISSUE TITLE
Update load-contributors to request all contributors of the org

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#961]
## Is your feature request related to a problem? Please describe

Right now we request outdated data from the old repository location.

## Describe the solution you'd like

Update the script to dynamically get contributors from all repos in the organisation, merge their contribution count and then put the results in the current json file.

**Comment by marikadeveloper** [comment]
I can try to do it 😁

**Comment by Idrinth** [comment]
> I can try to do it 😁

Make sure to use an API-Token while testing, you only have 60 requests/hour otherwise :)
